export DB_NAME=postgres_database_name
export PG_USER=postgres_user
export PG_PASSWORD=postgres_password
export PG_PORT=postgres_port
export PG_HOST=postgres_host
export TWITTER_PEU=twitter_phone_number/email/username
export TWITTER_PASSWORD=twitter_password